# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(vetiver)
library(rapidoc)
b <- board_folder(path = "/tmp/test")
m <- vetiver_pin_read(b, "cars_linear")

#* @plumber
function(pr) {
    pr %>% vetiver_pr_predict(m)
}
