#' Write a deployable Plumber file for a modelops object
#'
#' Use `modelops_write_plumber()` to create a `plumber.R` file for a
#' [modelops()] object that has been versioned and stored via
#' [modelops_pin_write()].
#'
#' @inheritParams pins::pin_read
#' @param file A path to write the Plumber file. Defaults to `plumber.R` in the
#' working directory. See [plumber::plumb()] for naming precedence rules.
#'
#' @details
#' By default, this function will find and use the latest version of the model;
#' the model API (when deployed) will be linked to that specific version. You
#' can override this default behavior by choosing a specific `version`.
#'
#' @return
#' The content of the `plumber.R` file, invisibly.
#'
#' @importFrom glue glue
#' @importFrom glue glue_collapse
#' @export
#'
#' @examples
#' library(pins)
#' tmp <- tempfile()
#' b <- board_temp(versioned = TRUE)
#' cars_lm <- lm(mpg ~ ., data = mtcars)
#' m <- modelops(cars_lm, "cars_linear", b)
#' modelops_pin_write(m)
#'
#' modelops_write_plumber(b, "cars_linear", file = tmp)
#'
modelops_write_plumber <- function(board, name, version = NULL,
                                   file = "plumber.R") {

    if (board$versioned) {
        if (rlang::is_null(version)) {
            version <- pins::pin_versions(board, name)
            version <- version$version
            version <- version[1]
        }
        pin_read <- glue('m <- modelops_pin_read(b, "{name}", version = "{version}")')
        m <- modelops_pin_read(board, name, version = version)
    } else {
        pin_read <- glue('m <- modelops_pin_read(b, "{name}")')
        m <- modelops_pin_read(board, name)
    }

    load_pkgs <- glue_collapse(glue("library({infra_pkgs})"), sep = "\n")
    beginning <- list("# Generated by the modelops package\n", load_pkgs)

    middle <- glue_required_pkgs(m$metadata$required_pkgs)

    board <- rlang::expr_deparse(pins::board_deparse(board))
    board <- glue('b <- {board}')

    plumber <- glue("\n
         #* @plumber
         function(pr) {{
             pr %>% modelops_pr_predict(m)
         }}
         ")
    end <- list(board, pin_read, plumber)

    readr::write_lines(c(beginning, middle, end), file = file)
}

infra_pkgs <- c("pins", "plumber", "modelops")


glue_required_pkgs <- function(required_pkgs) {
    if (!rlang::is_null(required_pkgs)) {
        required_pkgs <- glue_collapse(glue("    library({required_pkgs})"),
                                       sep = "\n")
        load_required_pkgs <- glue("\n
            if (FALSE) {{
            {required_pkgs}
            }}
            ")
        return(load_required_pkgs)
    }
    NULL
}


