#' Write a deployable Plumber file for a vetiver model
#'
#' Use `vetiver_write_plumber()` to create a `plumber.R` file for a
#' [vetiver_model()] that has been versioned and stored via
#' [vetiver_pin_write()].
#'
#' @inheritParams pins::pin_read
#' @param file A path to write the Plumber file. Defaults to `plumber.R` in the
#' working directory. See [plumber::plumb()] for naming precedence rules.
#' @param docs A character value matching a package for OpenAPI visual
#' documentation such as \pkg{rapidoc} (the default) or \pkg{redoc}. Use `NULL`
#' for default Plumber docs.
#'
#' @details
#' By default, this function will find and use the latest version of vetiver
#' model; the model API (when deployed) will be linked to that specific version.
#' You can override this default behavior by choosing a specific `version`.
#'
#' @return
#' The content of the `plumber.R` file, invisibly.
#'
#' @export
#'
#' @examples
#' library(pins)
#' tmp <- tempfile()
#' b <- board_temp(versioned = TRUE)
#' cars_lm <- lm(mpg ~ ., data = mtcars)
#' v <- vetiver_model(cars_lm, "cars_linear", b)
#' vetiver_pin_write(v)
#'
#' vetiver_write_plumber(b, "cars_linear", file = tmp)
#'
vetiver_write_plumber <- function(board, name, version = NULL,
                                  file = "plumber.R",
                                  docs = "rapidoc") {

    if (board$versioned) {
        if (is_null(version)) {
            version <- pins::pin_versions(board, name)
            version <- version[["version"]]
            version <- version[[1]]
        }
        pin_read <- glue('m <- vetiver_pin_read(b, "{name}", version = "{version}")')
        m <- vetiver_pin_read(board, name, version = version)
    } else {
        pin_read <- glue('m <- vetiver_pin_read(b, "{name}")')
        m <- vetiver_pin_read(board, name)
    }

    load_infra_pkgs <- glue_collapse(glue("library({infra_pkgs})"), sep = "\n")
    doc_pkg <- if (is_null(docs)) NULL else glue("library({docs})")
    load_required_pkgs <- glue_required_pkgs(m$metadata$required_pkgs)

    board <- rlang::expr_deparse(pins::board_deparse(board))
    board <- glue('b <- {board}')

    plumber <- glue("\n
         #* @plumber
         function(pr) {{
             pr %>% vetiver_pr_predict(m)
         }}
         ")

    ret <- compact(list(
        "# Generated by the vetiver package; edit with care\n",
        load_infra_pkgs,
        doc_pkg,
        load_required_pkgs,
        board,
        pin_read,
        plumber
    ))
    readr::write_lines(ret, file = file)
}

infra_pkgs <- c("pins", "plumber", "vetiver")


glue_required_pkgs <- function(required_pkgs) {
    if (!is_null(required_pkgs)) {
        required_pkgs <- sort(required_pkgs)
        required_pkgs <- glue_collapse(glue("    library({required_pkgs})"),
                                       sep = "\n")
        load_required_pkgs <- glue("\n
            # Packages needed to generate model predictions
            if (FALSE) {{
            {required_pkgs}
            }}
            ")
        return(load_required_pkgs)
    }
    NULL
}


